services:
  - type: web
    name: enjoyable-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5"