services:
  - type: web
    name: enjoyable-app
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet -w 1
    envVars:
      - key: FLASK_ENV
        value: production
    rootDir: backend