services:
  - type: web
    name: livecast-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tempcoderunnerfile.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    runtime: python
    plan: free
    region: oregon
    startCommand: gunicorn app:app --chdir backend --worker-class eventlet -w 1