services:
  - type: web
    name: LiveCast
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --worker-class eventlet -w 1
    envVars:
      - key: FLASK_ENV
        value: production
