services:
  - type: web
    name: video-platform-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/simple_video_app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"