# services:
#   - type: web
#     name: emjoyable-app
#     env: python
#     buildCommand: pip install -r backend/requirements.txt
#     startCommand: gunicorn backend.app:app --worker-class eventlet -w 1
#     envVars:
#       - key: PYTHONPATH
#         value: backend
services:
  - type: web
    name: enjoyable-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet -w 1
    envVars:
      - key: FLASK_ENV
        value: production
    rootDir: backend